service:
  name: auth-service

plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  region: eu-west-1
  environment:
    AUTH0_PUBLIC_KEY: ${file(secret.pem)}

functions:
  auth:
    handler: src/handlers/auth.handler
    cors: true
  publicEndpoint:
    handler: src/handlers/public.handler
    events:
      - http:
          path: public
          method: POST
          cors: true
  privateEndpoint:
    handler: src/handlers/private.handler
    events:
      - http:
          path: private
          method: POST
          authorizer: auth
          cors: true

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse: ${file(resources/GatewayResponse.yml):GatewayResponse}
    AuthFailureGatewayResponse: ${file(resources/AuthFailureGatewayResponse.yml):AuthFailureGatewayResponse}

custom:
  bundle:
    linting: false
